# Generated by Django 5.1.3 on 2025-01-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_photographer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='available_photographer',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='available_photographer',
            name='package',
        ),
        migrations.AddField(
            model_name='available_photographer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Hourly rate in INR', max_digits=10),
            preserve_default=False,
        ),
    ]
