# Generated by Django 5.1.3 on 2025-01-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_available_photographer_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='requirements',
            new_name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.AddField(
            model_name='booking',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='hours_needed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='photographer_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.available_photographer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
