# Generated by Django 5.1.3 on 2025-01-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_requirements_booking_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_time',
        ),
    ]
