# Generated by Django 5.1.3 on 2025-01-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_booking_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_duration',
        ),
    ]
